ci tests update

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -1,75 +1,79 @@
 name: CI
 
 on:
-  push:
-    branches:
-      - main
+    push:
+        branches:
+            - main
 
-  pull_request:
-    branches:
-      - main
+    pull_request:
+        branches:
+            - main
 
 concurrency:
-  group: ci-${{ github.event.pull_request.number || github.ref }}
-  cancel-in-progress: true
-
+    group: ci-${{ github.event.pull_request.number || github.ref }}
+    cancel-in-progress: true
 
 jobs:
+    # ! uncomment when finished setting up
+    # check-workflow-files:
+    #   runs-on: ubuntu-latest
+    #   steps:
+    #   # See: https://github.com/dorny/paths-filter
+    #   #  quite useful, can be used to trigger certain tests
+    #   #  only when certain files change.
+    #     - uses: actions/checkout@v4
+    #     - uses: dorny/paths-filter@v3
+    #       id: changes
+    #       with:
+    #         filters: |
+    #           workflow:
+    #             - '.github/workflows/**'
+    #     - name: Fail if workflow files are changed
+    #       run: exit 1
+    #       if: steps.changes.outputs.workflow == 'true'
 
-  # ! uncomment when finished setting up
-  # check-workflow-files:
-  #   runs-on: ubuntu-latest
-  #   steps:
-  #   # See: https://github.com/dorny/paths-filter
-  #   #  quite useful, can be used to trigger certain tests 
-  #   #  only when certain files change.
-  #     - uses: actions/checkout@v4
-  #     - uses: dorny/paths-filter@v3
-  #       id: changes
-  #       with:
-  #         filters: |
-  #           workflow:
-  #             - '.github/workflows/**'
-  #     - name: Fail if workflow files are changed
-  #       run: exit 1
-  #       if: steps.changes.outputs.workflow == 'true'
+    sveltecheck:
+        runs-on: ubuntu-latest
+        steps:
+            - uses: actions/checkout@v4
+            - uses: actions/setup-node@v4
+              with:
+                  node-version: 22
+                  cache: "npm"
 
-  sveltecheck:
-    runs-on: ubuntu-latest
-    steps:
-      - uses: actions/checkout@v4
-      - uses: actions/setup-node@v4
-        with:
-          node-version: 22
-          cache: 'npm'
+            - name: Install
+              run: npm ci
 
-      - name: Install
-        run: npm ci
+            - name: Check
+              run: npm run check
 
-      - name: Check
-        run: npm run check
+    test:
+        timeout-minutes: 60
+        runs-on: ubuntu-latest
+        steps:
+            - uses: actions/checkout@v4
+            - uses: actions/setup-node@v4
+              with:
+                  node-version: 22
 
-  test:
-    timeout-minutes: 60
-    runs-on: ubuntu-latest
-    steps:
-    - uses: actions/checkout@v4
-    - uses: actions/setup-node@v4
-      with:
-        node-version: lts/*
-    - name: Install dependencies
-      run: npm ci
-    - name: Install Playwright Browsers
-      run: npx playwright install --with-deps
-    - name: Playwright tests
-      run: npm test
-    - uses: actions/upload-artifact@v4
-      if: ${{ !cancelled() }}
-      with:
-        name: playwright-report
-        path: playwright-report/
-        retention-days: 30
+            - name: Install dependencies
+              run: npm ci
 
+            - name: Install Playwright
+              run: npm install playwright-chromium
+
+            - name: Install Playwright Browsers
+              run: npx playwright install chromium
+
+            - name: Playwright tests
+              run: npm test
+              
+            - uses: actions/upload-artifact@v4
+              if: ${{ !cancelled() }}
+              with:
+                  name: playwright-report
+                  path: playwright-report/
+                  retention-days: 30
 #   test:
 #     runs-on: ${{ matrix.os }}
 
@@ -96,7 +100,7 @@ jobs:
 
 #       - name: Playwright Install
 #         run: npx playwright install --with-deps
-        
+
 #       - name: Browser Tests
 #         run: npm run test
 
